import 'package:cricstreak/Screens/ARScreen/View/ARPage.dart';
import 'package:cricstreak/Screens/BatPage/View/BatPage.dart';
import 'package:cricstreak/Screens/BowlScreen/View/BowlPage.dart';
import 'package:cricstreak/Screens/CreateTeam/model/PlayerDetailModel.dart';
import 'package:cricstreak/Screens/CreateTeam/model/TeamModel.dart';
import 'package:cricstreak/Screens/WKScreen/View/WKPage.dart';
import 'package:flutter/cupertino.dart';
import 'package:get/get.dart';

class CreateTeamController extends GetxController {
  RxList<Widget> Screens = [
    WKPage(),
    BatPage(),
    ARPage(),
    BowlPage(),
  ].obs;
  RxList<PlayerDetailModel> wkList = <PlayerDetailModel>[
    PlayerDetailModel(
        firstName: "Dinesh",
        lastName: "Kartik",
        teamName: "RCB",
        selected: false,
        avgPts: 90,
        selBy: 74,
        credit: 8.5,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/13.png"),
    PlayerDetailModel(
        firstName: "Anuj",
        lastName: "Rawat",
        teamName: "RCB",
        selected: false,
        avgPts: 76,
        selBy: 15,
        credit: 6.5,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/534.png"),
    PlayerDetailModel(
        firstName: "Finn",
        lastName: "Allen",
        teamName: "RCB",
        selected: false,
        avgPts: 70,
        selBy: 10,
        credit: 5.5,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/595.png"),
    PlayerDetailModel(
        firstName: "MS",
        lastName: "Dhoni",
        teamName: "CSK",
        selected: false,
        avgPts: 130,
        selBy: 40,
        credit: 9.5,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/57.png"),
    PlayerDetailModel(
        firstName: "Devon",
        lastName: "Conway",
        teamName: "CSK",
        selected: false,
        avgPts: 290,
        selBy: 93,
        credit: 9.5,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/601.png"),
  ].obs;
  RxList<PlayerDetailModel> batList = <PlayerDetailModel>[
    PlayerDetailModel(
        firstName: "Virat",
        lastName: "Kohli",
        teamName: "RCB",
        selected: false,
        avgPts: 380,
        selBy: 98,
        credit: 9.5,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/2.png"),
    PlayerDetailModel(
        firstName: "Faf Du",
        lastName: "Plessis",
        teamName: "RCB",
        selected: false,
        avgPts: 375,
        selBy: 97,
        credit: 9.5,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/94.png"),
    PlayerDetailModel(
        firstName: "Rajat",
        lastName: "Patidar",
        teamName: "RCB",
        selected: false,
        avgPts: 90,
        selBy: 10,
        credit: 5.5,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl: ""),
    PlayerDetailModel(
        firstName: "Suyash S",
        lastName: "Prabhudessai",
        teamName: "RCB",
        selected: false,
        avgPts: 30,
        selBy: 5,
        credit: 5,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/598.png"),
    PlayerDetailModel(
        firstName: "Ruturaj",
        lastName: "Gaikwad",
        teamName: "CSK",
        selected: false,
        avgPts: 290,
        selBy: 93,
        credit: 9.5,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/102.png"),
    PlayerDetailModel(
        firstName: "Ambati",
        lastName: "Rayudu",
        teamName: "CSK",
        selected: false,
        avgPts: 120,
        selBy: 60,
        credit: 8,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/60.png"),
    PlayerDetailModel(
        firstName: "Ajinkya",
        lastName: "Rahane",
        teamName: "CSK",
        selected: false,
        avgPts: 130,
        selBy: 64,
        credit: 8,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/44.png"),
    PlayerDetailModel(
        firstName: "Shaik",
        lastName: "Rasheed",
        teamName: "CSK",
        selected: false,
        avgPts: 0,
        selBy: 0,
        credit: 0,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/778.png"),
    PlayerDetailModel(
        firstName: "Subhranshu",
        lastName: "Senapati",
        teamName: "CSK",
        selected: false,
        avgPts: 0,
        selBy: 0,
        credit: 0,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/971.png"),
  ].obs;
  RxList<PlayerDetailModel> arList = <PlayerDetailModel>[
    PlayerDetailModel(
        firstName: "Glenn",
        lastName: "Maxwell",
        teamName: "RCB",
        selected: false,
        avgPts: 380,
        selBy: 98,
        credit: 9.5,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/28.png"),
    PlayerDetailModel(
        firstName: "Shahbaz",
        lastName: "Ahmad",
        teamName: "RCB",
        selected: false,
        avgPts: 75,
        selBy: 57,
        credit: 6.5,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/523.png"),
    PlayerDetailModel(
        firstName: "Mahipal",
        lastName: "Lomror",
        teamName: "RCB",
        selected: false,
        avgPts: 90,
        selBy: 50,
        credit: 6.5,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/184.png"),
    PlayerDetailModel(
        firstName: "David",
        lastName: "Willey",
        teamName: "RCB",
        selected: false,
        avgPts: 120,
        selBy: 65,
        credit: 7,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/90.png"),
    PlayerDetailModel(
        firstName: "Manoj",
        lastName: "Bhandage",
        teamName: "RCB",
        selected: false,
        avgPts: 0,
        selBy: 0,
        credit: 0,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/102.png"),
    PlayerDetailModel(
        firstName: "Michael",
        lastName: "Bracewell",
        teamName: "RCB",
        selected: false,
        avgPts: 120,
        selBy: 60,
        credit: 8,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/1465.png"),
    PlayerDetailModel(
        firstName: "Will",
        lastName: "Jacks",
        teamName: "RCB",
        selected: false,
        avgPts: 120,
        selBy: 60,
        credit: 8,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl: ""),
    PlayerDetailModel(
        firstName: "Wayne",
        lastName: "Parnell",
        teamName: "RCB",
        selected: false,
        avgPts: 120,
        selBy: 60,
        credit: 8,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl: ""),
    PlayerDetailModel(
        firstName: "Sonu",
        lastName: "Yadav",
        teamName: "RCB",
        selected: false,
        avgPts: 0,
        selBy: 0,
        credit: 0,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/1940.png"),
    PlayerDetailModel(
        firstName: "Ravindra",
        lastName: "Jadeja",
        teamName: "CSK",
        selected: false,
        avgPts: 210,
        selBy: 89,
        credit: 8.5,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/46.png"),
    PlayerDetailModel(
        firstName: "Ben",
        lastName: "Stokes",
        teamName: "CSK",
        selected: false,
        avgPts: 0,
        selBy: 0,
        credit: 0,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/177.png"),
    PlayerDetailModel(
        firstName: "Dwaine",
        lastName: "Pretorius",
        teamName: "CSK",
        selected: false,
        avgPts: 0,
        selBy: 0,
        credit: 0,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/289.png"),
    PlayerDetailModel(
        firstName: "Moeen",
        lastName: "Ali",
        teamName: "CSK",
        selected: false,
        avgPts: 190,
        selBy: 60,
        credit: 8,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/206.png"),
    PlayerDetailModel(
        firstName: "Rajvardhan",
        lastName: "Hangargekar",
        teamName: "CSK",
        selected: false,
        avgPts: 0,
        selBy: 0,
        credit: 0,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/783.png"),
    PlayerDetailModel(
        firstName: "Nishant",
        lastName: "Sindhu",
        teamName: "CSK",
        selected: false,
        avgPts: 0,
        selBy: 0,
        credit: 0,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/791.png"),
    PlayerDetailModel(
        firstName: "Kyle",
        lastName: "Jamieson",
        teamName: "CSK",
        selected: false,
        avgPts: 0,
        selBy: 0,
        credit: 0,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/382.png"),
    PlayerDetailModel(
        firstName: "Mitchell",
        lastName: "Santner",
        teamName: "CSK",
        selected: false,
        avgPts: 30,
        selBy: 6,
        credit: 5,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/75.png"),
    PlayerDetailModel(
        firstName: "K. Bhagath",
        lastName: "Varma",
        teamName: "CSK",
        selected: false,
        avgPts: 0,
        selBy: 0,
        credit: 0,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/577.png"),
    PlayerDetailModel(
        firstName: "Ajay",
        lastName: "Mandal",
        teamName: "CSK",
        selected: false,
        avgPts: 0,
        selBy: 0,
        credit: 0,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/1931.png"),
    PlayerDetailModel(
        firstName: "Shivam",
        lastName: "Dube",
        teamName: "CSK",
        selected: false,
        avgPts: 230,
        selBy: 76,
        credit: 8,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/211.png"),
  ].obs;
  RxList<PlayerDetailModel> bowlList = <PlayerDetailModel>[
    PlayerDetailModel(
        firstName: "Harshal",
        lastName: "Patel",
        teamName: "RCB",
        selected: false,
        avgPts: 280,
        selBy: 80,
        credit: 9,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/114.png"),
    PlayerDetailModel(
        firstName: "Karn",
        lastName: "Sharma",
        teamName: "RCB",
        selected: false,
        avgPts: 230,
        selBy: 57,
        credit: 7.5,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/98.png"),
    PlayerDetailModel(
        firstName: "Mohammed",
        lastName: "Siraj",
        teamName: "RCB",
        selected: false,
        avgPts: 310,
        selBy: 90,
        credit: 9.5,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/63.png"),
    PlayerDetailModel(
        firstName: "Josh",
        lastName: "Hazlewood",
        teamName: "RCB",
        selected: false,
        avgPts: 30,
        selBy: 5,
        credit: 6,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl: ""),
    PlayerDetailModel(
        firstName: "Siddarth",
        lastName: "Kaul",
        teamName: "RCB",
        selected: false,
        avgPts: 9,
        selBy: 3,
        credit: 5,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/64.png"),
    PlayerDetailModel(
        firstName: "Akash",
        lastName: "Deep",
        teamName: "RCB",
        selected: false,
        avgPts: 60,
        selBy: 5,
        credit: 5,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/1007.png"),
    PlayerDetailModel(
        firstName: "Wanindu",
        lastName: "Hasaranga",
        teamName: "RCB",
        selected: false,
        avgPts: 160,
        selBy: 45,
        credit: 8,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/377.png"),
    PlayerDetailModel(
        firstName: "Reece",
        lastName: "Topley",
        teamName: "RCB",
        selected: false,
        avgPts: 20,
        selBy: 20,
        credit: 5,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/574.png"),
    PlayerDetailModel(
        firstName: "Avinash",
        lastName: "Singh",
        teamName: "RCB",
        selected: false,
        avgPts: 0,
        selBy: 0,
        credit: 0,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/1939.png"),
    PlayerDetailModel(
        firstName: "Himanshu",
        lastName: "Sharma",
        teamName: "RCB",
        selected: false,
        avgPts: 0,
        selBy: 0,
        credit: 0,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/1568.png"),
    PlayerDetailModel(
        firstName: "Rajan",
        lastName: "Kumar",
        teamName: "RCB",
        selected: false,
        avgPts: 0,
        selBy: 0,
        credit: 05,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/1503.png"),
    PlayerDetailModel(
        firstName: "Vyshak Vijay",
        lastName: "Kumar",
        teamName: "RCB",
        selected: false,
        avgPts: 140,
        selBy: 65,
        credit: 6.5,
        point: 0,
        color: "0xff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl: ""),
    PlayerDetailModel(
        firstName: "Dipak",
        lastName: "Chahar",
        teamName: "CSK",
        selected: false,
        avgPts: 180,
        selBy: 85,
        credit: 9,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/91.png"),
    PlayerDetailModel(
        firstName: "Maheesh",
        lastName: "Theekshana",
        teamName: "CSK",
        selected: false,
        avgPts: 140,
        selBy: 60,
        credit: 8,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/629.png"),
    PlayerDetailModel(
        firstName: "Matheesha",
        lastName: "Pathirana",
        teamName: "CSK",
        selected: false,
        avgPts: 130,
        selBy: 64,
        credit: 8,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/1014.png"),
    PlayerDetailModel(
        firstName: "Mukesh",
        lastName: "Choudhary",
        teamName: "CSK",
        selected: false,
        avgPts: 0,
        selBy: 0,
        credit: 0,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/970.png"),
    PlayerDetailModel(
        firstName: "Prashant",
        lastName: "Solanki",
        teamName: "CSK",
        selected: false,
        avgPts: 0,
        selBy: 0,
        credit: 0,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/972.png"),
    PlayerDetailModel(
        firstName: "Simarjeet",
        lastName: "Singh",
        teamName: "CSK",
        selected: false,
        avgPts: 0,
        selBy: 0,
        credit: 0,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/622.png"),
    PlayerDetailModel(
        firstName: "Tushar",
        lastName: "Deshpande",
        teamName: "CSK",
        selected: false,
        avgPts: 120,
        selBy: 60,
        credit: 6.5,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/539.png"),
    PlayerDetailModel(
        firstName: "Akash",
        lastName: "Singh",
        teamName: "CSK",
        selected: false,
        avgPts: 0,
        selBy: 0,
        credit: 0,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/535.png"),
    PlayerDetailModel(
        firstName: "Sisanda",
        lastName: "Magala",
        teamName: "CSK",
        selected: false,
        avgPts: 0,
        selBy: 0,
        credit: 0,
        point: 0,
        color: "0xffffffff",
        capSelby: 0.0,
        vicecapSelby: 0.0,
        captain: false,
        vicecaptain: false,
        imageUrl:
            "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/745.png"),
  ].obs;
  Rx<TeamModel> FinalTeam = TeamModel(AR: <PlayerDetailModel>[].obs, Bat: <PlayerDetailModel>[].obs, Bowl: <PlayerDetailModel>[].obs, WK: <PlayerDetailModel>[].obs).obs;
  RxInt CVCSelected = 0.obs;
  RxMap<String, int> count = {
    "WK": 0,
    "BAT": 0,
    "AR": 0,
    "BOWL": 0,
  }.obs;
  RxInt PlayerCount = 0.obs;
  RxInt WKPCount = 0.obs;
  RxInt BATPCount = 0.obs;
  RxInt ARPCount = 0.obs;
  RxInt BOWLPCount = 0.obs;
  RxInt RCBPCount = 0.obs;
  RxInt CSKPCount = 0.obs;
  RxDouble CreditLeftCount = 100.0.obs;
}
